name: Sample GitHub Actions Workflow
on:
  push:
    branches:
      - master
      
      
  workflow_dispatch:

jobs:
  avni-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    

    - name: Set up environment variables
      run: |
          echo "export ANDROID_SDK_ROOT=$HOME/Library/Android/sdk" >> $GITHUB_ENV
          echo "export ANDROID_HOME=$HOME/Library/Android/sdk" >> $GITHUB_ENV
    - name: Install NVM and Node.js
      run: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install

    - name: Install project dependencies
      run: make deps

    - name: Copy dev.json.template to dev.json
      run: cp packages/openchs-android/config/env/dev.json.template packages/openchs-android/config/env/dev.json

    - name: Print a message
      run: echo "Hello, this is a sample GHA workflow!"
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Verify Java version
      run: java -version
    - name: Add Maven plugin to build.gradle
      run: |
          echo 'classpath 'org.apache.maven.plugins:maven-publish:3.0.0'' >> packages/openchs-android/build.gradle



    - name: Install Watchman
      run: |
        sudo apt-get update
        sudo apt-get install -y watchman
    


    - name: Generate keystore
      run: |
        cd packages/openchs-android/android/app
        keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=server" -alias bahmni -ext "SAN:c=DNS:localhost,IP:127.0.0.1" -keystore bahmni-release-key.keystore
        export BAHMNI_KEYSTORE_PASSWORD=password
        export BAHMNI_KEY_PASSWORD=password
  

    - name: Run make release_urlconfig_universal
      run: |
        export BAHMNI_KEYSTORE_PASSWORD=password
        export BAHMNI_KEY_PASSWORD=password
        make release_urlconfig_universal flavor='bahmni'
