name: Sample GitHub Actions Workflow
on:
  push:
    branches:
      - master
      
      
  workflow_dispatch:

jobs:
  avni-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print a message
      run: echo "Hello, this is a sample GHA workflow!"
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Verify Java version
      run: java -version
    - name: Install Node.js and npm
      uses: actions/setup-node@v3
      with:
        node-version: '16'  

    - name: Install npm dependencies
      run: |
        cd packages/openchs-android
        npm install
    - name: Build with Gradle
      run: |
        cd packages/openchs-android/android
        ./gradlew build --info --stacktrace

   
    - name: Install Watchman
      run: |
        sudo apt-get update
        sudo apt-get install -y watchman
    


    - name: Generate keystore
      run: |
        cd packages/openchs-android/android/app
        keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=server" -alias bahmni -ext "SAN:c=DNS:localhost,IP:127.0.0.1" -keystore bahmni-release-key.keystore
        export BAHMNI_KEYSTORE_PASSWORD=password
        export BAHMNI_KEY_PASSWORD=password
  

    - name: Run make release_urlconfig_universal
      run: |
        export BAHMNI_KEYSTORE_PASSWORD=password
        export BAHMNI_KEY_PASSWORD=password
        make release_urlconfig_universal flavor='bahmni'
